### ISSUE TITLE
Update tutorial to work with Breadboard `0.4.0`

### ISSUE THREAD

**Issue by dglazkov** [google/labs-prototypes#163]
shukri reports:

in  https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/docs/tutorial/tutorial-4.js

```
const diagram = board2.mermaid();                       
TypeError: board2.mermaid is not a function
```

in https://github.com/google/labs-prototypes/blob/main/seeds/breadboard/docs/tutorial/tutorial-6b.js

```
Error: Uncaught exception in node handler. Catch by wiring up the $error output.
    at #processCompletedNode (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/traversal/iterator.js:27:19)
    at TraversalMachineIterator.next (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/traversal/iterator.js:85:59)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BoardRunner.run (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/runner.js:90:26)
    at async BoardRunner.runOnce (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/runner.js:167:26)
    at async file:///workspaces/labs-prototypes/typscript_quickly/dist/main.js:13:16 {
  [cause]: {
    kind: 'error',
    error: Error: No graph found for slot "news"
        at Object.invoke (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/nodes/slot.js:27:19)
        at callHandler (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/handler.js:10:24)
        at BoardRunner.run (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/runner.js:128:19)
        at run.next (<anonymous>)
        at BoardRunner.runOnce (file:///workspaces/labs-prototypes/seeds/breadboard/dist/src/runner.js:167:26)
        at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
        at async file:///workspaces/labs-prototypes/typscript_quickly/dist/main.js:13:16,
    inputs: { slot: 'news', topic: 'Latest news on breadboards' },
    descriptor: { id: 'slot-3', type: 'slot', configuration: { slot: 'news' } }
  }
}
```

**Comment by seefeldb** [comment]
Ah, mermaid() is just on `Board` and not `BoardRunner`? We should probably move it there.

**Comment by dglazkov** [comment]
All done!
